import { useState } from 'react'
import { Bot, CheckCircle, Cloud, Eye, EyeOff, Loader2, Search, ShieldAlert, X, Zap } from 'lucide-react'
import * as api from '../api/client'

interface Props { open:boolean; onClose:()=>void; onSaved:()=>void }
type TestState='idle'|'testing'|'success'|'failed'
const llmProviders=['OpenAI','DeepSeek','通义千问','智谱','Moonshot','其他']
const searchProviders=['Bocha','Tavily','Serper','SerpApi','SearXNG','Brave','暂不配置']
function runtime(provider:string,custom:string){
 const preset:Record<string,{url:string;model:string}>={OpenAI:{url:'https://api.openai.com/v1',model:'gpt-4o-mini'},DeepSeek:{url:'https://api.deepseek.com',model:'deepseek-chat'},通义千问:{url:'https://dashscope.aliyuncs.com/compatible-mode/v1',model:'qwen-plus'},智谱:{url:'https://open.bigmodel.cn/api/paas/v4',model:'glm-4-flash'},Moonshot:{url:'https://api.moonshot.cn/v1',model:'moonshot-v1-8k'}}
 return {base_url:custom.trim() || preset[provider]?.url || '',model_name:preset[provider]?.model || ''}
}
export default function ApiConfigModal({open,onClose,onSaved}:Props){
 const [provider,setProvider]=useState('DeepSeek'),[apiKey,setApiKey]=useState(''),[baseUrl,setBaseUrl]=useState('')
 const [searchProvider,setSearchProvider]=useState('Bocha'),[searchKey,setSearchKey]=useState(''),[searchBase,setSearchBase]=useState('')
 const [baiduKey,setBaiduKey]=useState(''),[baiduSecret,setBaiduSecret]=useState(''),[ocrRisk,setOcrRisk]=useState(false)
 const [show,setShow]=useState<Record<string,boolean>>({}),[state,setState]=useState<TestState>('idle'),[message,setMessage]=useState('')
 if(!open)return null
 const toggle=(k:string)=>setShow(v=>({...v,[k]:!v[k]}))
 const handleTestLlm=async()=>{if(!apiKey.trim()){setState('failed');setMessage('请先填写大模型 API Key。');return}setState('testing');setMessage('正在测试大模型连接…');try{const r=runtime(provider,baseUrl);const x=await api.testProviderConfig({provider,api_key:apiKey.trim(),base_url:r.base_url,model_name:r.model_name});setState('success');setMessage(x.message||'大模型连接成功。')}catch(e){setState('failed');setMessage(e instanceof Error?e.message:'大模型连接失败')}}
 const handleTestSearch=async()=>{if(searchProvider!=='SearXNG'&&!searchKey.trim()){setState('failed');setMessage('该搜索服务需要 API Key。');return}setState('testing');setMessage('正在测试联网搜索接口…');try{const x=await api.testSearchConfig({search_provider:searchProvider,search_api_key:searchKey.trim(),search_base_url:searchBase.trim()});setState('success');setMessage(x.message||'联网搜索连接成功。')}catch(e){setState('failed');setMessage(e instanceof Error?e.message:'联网搜索失败')}}
 const handleTestOcr=async()=>{if(!ocrRisk){setState('failed');setMessage('请先确认云端 OCR 的资料上传风险。');return}if(!baiduKey.trim()||!baiduSecret.trim()){setState('failed');setMessage('请填写百度 API Key 与 Secret Key。');return}setState('testing');setMessage('正在测试百度云 OCR 鉴权…');try{const x=await api.testBaiduOcrConfig({baidu_api_key:baiduKey.trim(),baidu_secret_key:baiduSecret.trim(),risk_confirmed:true});setState('success');setMessage(x.message||'百度云 OCR 鉴权成功。')}catch(e){setState('failed');setMessage(e instanceof Error?e.message:'百度云 OCR 测试失败')}}
 const handleSave=async()=>{try{const r=runtime(provider,baseUrl);if((baiduKey||baiduSecret)&&!ocrRisk)throw new Error('保存百度云 OCR 配置前必须确认资料上传网络风险。');await api.saveProviderConfig({provider,api_key:apiKey.trim(),base_url:r.base_url,model_name:r.model_name,search_provider:searchProvider,search_api_key:searchKey.trim(),search_base_url:searchBase.trim(),baidu_api_key:baiduKey.trim(),baidu_secret_key:baiduSecret.trim(),ocr_provider:'baidu_paddleocr_vl',ocr_risk_confirmed:ocrRisk});setState('success');setMessage('配置已保存。第三方密钥只保存在后端配置中，不会回显到页面。');onSaved()}catch(e){setState('failed');setMessage(e instanceof Error?e.message:'保存失败')}}
 const Password=({name,value,onChange,placeholder}:{name:string;value:string;onChange:(v:string)=>void;placeholder:string})=><div className="relative"><input type={show[name]?'text':'password'} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="input-styled w-full pr-10"/><button type="button" onClick={()=>toggle(name)} className="absolute right-2 top-2 text-foreground-muted">{show[name]?<EyeOff size={17}/>:<Eye size={17}/>}</button></div>
 return <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
   {/* 安全配置弹窗仅允许显式关闭，点击遮罩不会关闭。 */}<div className="absolute inset-0 bg-black/62 backdrop-blur-[2px]"/>
   <div className="relative max-h-[92vh] w-full max-w-[700px] overflow-auto rounded-xl border border-edge bg-white shadow-2xl modal-pop">
    <div className="sticky top-0 z-10 flex items-start justify-between border-b border-edge bg-[#f3f5f8] px-6 py-5"><div><h2 className="text-xl font-semibold text-foreground">服务配置</h2><p className="mt-1 text-xs text-foreground-secondary">模型、联网搜索与云端文档解析均可独立配置。</p></div><button onClick={onClose} aria-label="关闭" className="rounded-full p-2 text-foreground-secondary hover:bg-edge"><X size={18}/></button></div>
    <div className="space-y-8 p-6">
      <section><div className="mb-4 flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#e6f0ff] text-[#0d4ec9]"><Bot size={18}/></span><h3 className="font-semibold">大模型（OpenAI 兼容接口）</h3></div><div className="grid gap-3 md:grid-cols-2"><label><span className="mb-1 block text-sm">服务商</span><select className="input-styled w-full" value={provider} onChange={e=>setProvider(e.target.value)}>{llmProviders.map(x=><option key={x}>{x}</option>)}</select></label><label><span className="mb-1 block text-sm">Base URL（可覆盖预设）</span><input className="input-styled w-full" value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} placeholder="https://.../v1"/></label><label className="md:col-span-2"><span className="mb-1 block text-sm">API Key</span><Password name="llm" value={apiKey} onChange={setApiKey} placeholder="sk-..."/></label></div><button onClick={handleTestLlm} className="btn-secondary mt-3"><Zap size={15}/> 测试大模型</button></section>
      <section><div className="mb-4 flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-emerald-50 text-emerald-700"><Search size={18}/></span><h3 className="font-semibold">联网搜索</h3></div><div className="grid gap-3 md:grid-cols-2"><label><span className="mb-1 block text-sm">搜索服务</span><select className="input-styled w-full" value={searchProvider} onChange={e=>setSearchProvider(e.target.value)}>{searchProviders.map(x=><option key={x}>{x}</option>)}</select></label><label><span className="mb-1 block text-sm">Endpoint（SearXNG 必填，可选覆盖）</span><input className="input-styled w-full" value={searchBase} onChange={e=>setSearchBase(e.target.value)} placeholder="https://.../search"/></label><label className="md:col-span-2"><span className="mb-1 block text-sm">API Key（SearXNG 可为空）</span><Password name="search" value={searchKey} onChange={setSearchKey} placeholder="联网搜索 API Key"/></label></div><button onClick={handleTestSearch} className="btn-secondary mt-3"><Search size={15}/> 测试联网搜索</button></section>
      <section><div className="mb-4 flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-amber-50 text-amber-700"><Cloud size={18}/></span><div><h3 className="font-semibold">百度智能云：文档解析（PaddleOCR-VL）</h3><p className="text-xs text-foreground-muted">用于扫描件、复杂版面、表格、阅读顺序和跨页内容；不安装、不配置本地 OCR。</p></div></div><div className="rounded-card border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><div className="flex gap-2"><ShieldAlert className="mt-0.5 shrink-0" size={17}/><span>选择“云端版面/表格解析”后，原始文件会被上传至百度智能云处理。请不要上传未获授权的涉密、个人敏感或受保密义务约束的资料。</span></div></div><div className="mt-3 grid gap-3 md:grid-cols-2"><label><span className="mb-1 block text-sm">API Key</span><Password name="baiduKey" value={baiduKey} onChange={setBaiduKey} placeholder="百度应用 API Key"/></label><label><span className="mb-1 block text-sm">Secret Key</span><Password name="baiduSecret" value={baiduSecret} onChange={setBaiduSecret} placeholder="百度应用 Secret Key"/></label></div><label className="mt-3 flex items-start gap-2 rounded-card border border-edge p-3 text-sm"><input className="mt-1" type="checkbox" checked={ocrRisk} onChange={e=>setOcrRisk(e.target.checked)}/><span>我已理解并确认：使用云端 OCR 时文件将通过网络传输至百度智能云。</span></label><button onClick={handleTestOcr} className="btn-secondary mt-3"><Cloud size={15}/> 测试百度云 OCR 鉴权</button></section>
      {message&&<div className={`rounded-card border p-3 text-sm ${state==='failed'?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-800'}`}>{state==='testing'&&<Loader2 className="mr-2 inline animate-spin" size={15}/>} {state==='success'&&<CheckCircle className="mr-2 inline" size={15}/>} {message}</div>}
    </div>
    <div className="sticky bottom-0 flex justify-end gap-3 border-t border-edge bg-white px-6 py-4"><button onClick={onClose} className="btn-secondary">取消</button><button onClick={handleSave} className="btn-primary bg-[#002440] hover:bg-navy-light">保存配置</button></div>
   </div>
 </div>
}
