import { useEffect, useMemo, useRef, useState } from 'react'
import { CheckCircle, Cloud, FileUp, Loader2, Square, Upload, X } from 'lucide-react'
import type { KnowledgeBaseType, KnowledgeDocument } from '../types'
import * as api from '../api/client'

interface Props { open:boolean;onClose:()=>void;projectId:string;defaultKnowledgeBase?:KnowledgeBaseType;onUploaded:(doc:KnowledgeDocument)=>void;existingDocuments?:KnowledgeDocument[];onViewKnowledge?:()=>void }
type Step='select'|'uploading'|'parsing'|'summarizing'|'vectorizing'|'done'
const categories=['甲方资料','政策法规','技术标准','案例参考','会议纪要','评审意见','上位规划','控规图则','其他']
const stepText:Record<Step,string>={select:'选择文件',uploading:'上传中',parsing:'结构化解析中',summarizing:'文档摘要生成中',vectorizing:'索引与向量化中',done:'已入库'}
const inferCategory=(name:string)=>name.includes('会议')?'会议纪要':name.includes('评审')?'评审意见':name.includes('规划')?'上位规划':'甲方资料'
export default function UploadModal({open,onClose,projectId,defaultKnowledgeBase='project',onUploaded,existingDocuments=[],onViewKnowledge}:Props){
 const input=useRef<HTMLInputElement|null>(null), controller=useRef<AbortController|null>(null)
 const [step,setStep]=useState<Step>('select'),[files,setFiles]=useState<File[]>([]),[knowledgeBase,setKnowledgeBase]=useState<KnowledgeBaseType>(defaultKnowledgeBase),[category,setCategory]=useState('甲方资料'),[tags,setTags]=useState('甲方资料,待核验'),[generateSummary,setGenerateSummary]=useState(false),[useCloudOcr,setUseCloudOcr]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState(''),[done,setDone]=useState<KnowledgeDocument[]>([]),[duplicates,setDuplicates]=useState<string[]>([]),[approvedDup,setApprovedDup]=useState(false)
 useEffect(()=>{if(!open){controller.current?.abort();controller.current=null;setStep('select');setFiles([]);setKnowledgeBase(defaultKnowledgeBase);setCategory('甲方资料');setTags('甲方资料,待核验');setGenerateSummary(false);setUseCloudOcr(false);setProgress(0);setError('');setDone([]);setDuplicates([]);setApprovedDup(false)}},[open,defaultKnowledgeBase])
 const fileLabel=useMemo(()=>files.length===0?'':files.length===1?files[0].name:`已选择 ${files.length} 个文件`,[files])
 if(!open)return null
 const choose=(list:FileList|null)=>{const next=Array.from(list||[]);if(!next.length)return;setFiles(next);setCategory(inferCategory(next[0].name));setError('')}
 const findDuplicates=async()=>{let docs=existingDocuments.filter(d=>d.knowledgeBase===knowledgeBase&&(knowledgeBase==='general'||d.projectId===projectId));try{docs=await api.listDocuments({knowledgeBase,projectId:knowledgeBase==='project'?projectId:undefined})}catch{}const names=new Set(docs.map(d=>d.fileName.toLowerCase().trim()));return files.filter(f=>names.has(f.name.toLowerCase().trim())).map(f=>f.name)}
 const waitReady=async(doc:KnowledgeDocument)=>{let latest=doc;for(let i=0;i<120;i++){if(latest.parseStatus==='ready'||latest.parseStatus==='failed')return latest;await new Promise(r=>window.setTimeout(r,800));try{latest=await api.getDocument(doc.id);setStep(latest.parseStatus==='summarizing'?'summarizing':latest.parseStatus==='vectorizing'?'vectorizing':'parsing')}catch{return latest}}return latest}
 const runUpload=async()=>{setStep('uploading');setProgress(0);setError('');controller.current=new AbortController();try{const all:KnowledgeDocument[]=[];for(let i=0;i<files.length;i++){const base=(i/files.length)*100;const doc=await api.uploadFileResumable(files[i],{knowledgeBase,projectId:knowledgeBase==='project'?projectId:undefined,category,tags,generateSummary,useCloudOcr},(received,total)=>setProgress(Math.round(base+(received/total)*(100/files.length))),controller.current.signal);setStep('parsing');all.push(await waitReady(doc))}setDone(all);setStep('done')}catch(e){if(controller.current?.signal.aborted){setError('上传已中断。未完成的临时分片已请求服务端清理。')}else setError(e instanceof Error?e.message:'上传或解析失败');setStep('select')}finally{controller.current=null}}
 const start=async()=>{if(!files.length)return;if(!approvedDup){const same=await findDuplicates();if(same.length){setDuplicates(same);return}}await runUpload()}
 const cancel=()=>{controller.current?.abort()}
 const commit=()=>done.forEach(onUploaded)
 return <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
   {/* 点击遮罩不关闭弹窗，避免上传资料时误操作。 */}<div className="absolute inset-0 bg-black/40 backdrop-blur-[2px]"/>
   <div className="relative max-h-[92vh] w-full max-w-[680px] overflow-auto rounded-xl border border-edge bg-white shadow-xl modal-pop">
    <div className="sticky top-0 z-10 flex justify-between border-b border-edge bg-canvas px-6 py-4"><div><h2 className="text-lg font-semibold">上传资料</h2><p className="mt-1 text-xs text-foreground-muted">支持 Word、PDF、PPT、Excel、图片、TXT、Markdown；上传过程可中断。</p></div>{step==='select'&&<button onClick={onClose} className="rounded-card p-1 text-foreground-muted hover:bg-edge"><X size={20}/></button>}</div>
    {step==='select'&&<div className="space-y-5 p-6"><section><span className="block text-sm font-medium">上传文件</span><input ref={input} className="hidden" type="file" multiple accept=".pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.txt,.md,.png,.jpg,.jpeg,.webp" onChange={e=>choose(e.target.files)}/><button type="button" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files)}} className={`mt-2 flex min-h-[136px] w-full flex-col items-center justify-center rounded-xl border border-dashed px-5 py-6 ${files.length?'border-primary bg-primary-light/70 text-primary':'border-edge bg-canvas text-foreground-secondary hover:border-primary/40'}`}><FileUp size={30}/><span className="mt-3 text-sm font-medium">{fileLabel||'点击选择文件，或将文件拖拽到这里'}</span><span className="mt-1 text-xs text-foreground-muted">含 Word、PDF、PPT、Excel；旧版 Office 将提示转换或云端解析</span></button>{files.length>1&&<div className="mt-2 max-h-24 overflow-auto rounded-card border border-edge p-2 text-xs">{files.map(f=><div key={`${f.name}-${f.size}`} className="truncate py-0.5">{f.name}</div>)}</div>}</section>
      <div className="grid gap-4 md:grid-cols-2"><label><span className="mb-1 block text-sm">入库位置</span><select className="input-styled w-full" value={knowledgeBase} onChange={e=>setKnowledgeBase(e.target.value as KnowledgeBaseType)}><option value="project">当前项目知识库</option><option value="general">通用知识库</option></select></label><label><span className="mb-1 block text-sm">资料类型</span><select className="input-styled w-full" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label className="md:col-span-2"><span className="mb-1 block text-sm">标签</span><input className="input-styled w-full" value={tags} onChange={e=>setTags(e.target.value)} placeholder="多个标签用逗号分隔"/></label></div>
      <label className="flex items-start gap-2 rounded-card border border-edge bg-canvas p-3 text-sm"><input className="mt-1" type="checkbox" checked={generateSummary} onChange={e=>setGenerateSummary(e.target.checked)}/><span><b>生成摘要</b><span className="ml-2 text-xs text-foreground-muted">可选；不勾选也会保留可引用的正文与表格。</span></span></label>
      <label className="flex items-start gap-2 rounded-card border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><input className="mt-1" type="checkbox" checked={useCloudOcr} onChange={e=>setUseCloudOcr(e.target.checked)}/><Cloud className="mt-0.5 shrink-0" size={16}/><span><b>使用百度云端版面/表格解析</b><br/><span className="text-xs">需要先在服务配置中保存并确认云端传输风险；不选择则只使用本地文档解析，绝不启动本地 OCR。</span></span></label>
      {error&&<div className="rounded-card border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
      <div className="flex justify-end gap-3"><button onClick={onClose} className="btn-secondary">取消</button><button onClick={start} disabled={!files.length} className="btn-primary"><Upload size={16}/>开始上传</button></div>
    </div>}
    {step!=='select'&&step!=='done'&&<div className="flex flex-col items-center gap-5 p-10 text-center"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-primary-light"><Loader2 size={32} className="animate-spin text-primary"/></div><div><h3 className="font-semibold">{stepText[step]}</h3><p className="mt-1 text-sm text-foreground-secondary">{fileLabel}</p></div><div className="h-2 w-full max-w-sm overflow-hidden rounded-full bg-canvas"><div className="h-full bg-primary transition-all" style={{width:`${Math.max(progress,step==='uploading'?1:35)}%`}}/></div><p className="text-xs text-foreground-muted">上传 → 结构化版面/表格解析 → 索引 → 可用于对话</p><button onClick={cancel} className="btn-secondary text-red-700"><Square size={14}/> 中断上传</button></div>}
    {step==='done'&&<div className="flex flex-col items-center gap-4 p-8 text-center"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-status-active/10"><CheckCircle size={32} className="text-status-active"/></div><div><h3 className="font-semibold">资料已入库，可用于问答</h3><p className="mt-1 text-sm text-foreground-secondary">已入库 {done.length} 个文件，识别出的表格会作为可检索资料块。</p></div><div className="w-full rounded-card border border-edge bg-canvas p-3 text-left text-sm">{done.map(d=><div key={d.id} className="border-b border-edge-light py-1 last:border-0"><b>{d.fileName}</b><span className="ml-2 text-xs text-foreground-muted">{d.parserName||'结构化解析'} · {d.tableCount||0} 张表格 · {d.ocrStatus||'本地解析'}</span></div>)}</div><div className="flex gap-3"><button onClick={()=>{commit();onClose()}} className="btn-primary">回到工作台提问</button><button onClick={()=>{commit();onClose();onViewKnowledge?.()}} className="btn-secondary">查看知识库</button></div></div>}
   </div>
   {duplicates.length>0&&step==='select'&&<div className="absolute inset-0 z-10 flex items-center justify-center bg-black/20 p-4"><div className="w-full max-w-md rounded-card bg-white p-5 shadow-xl"><h3 className="font-semibold">发现同名文件</h3><p className="mt-2 text-sm text-foreground-secondary">继续上传会新增同名资料，不会覆盖原文件。</p><div className="mt-2 rounded-card bg-canvas p-2 text-xs">{duplicates.map(x=><div key={x}>{x}</div>)}</div><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setDuplicates([])} className="btn-secondary">返回</button><button onClick={()=>{setDuplicates([]);setApprovedDup(true);void runUpload()}} className="btn-primary">继续上传</button></div></div></div>}
 </div>
}
